# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["charlson.py"]

doc_url = "https://hmelberg.github.io/pinga/"

git_url = "https://github.com/hmelberg/pinga/tree/master/"

def custom_doc_links(name): return None
